wandb_version: 1

learning_rate:
  desc: null
  value: 3.0e-06
epochs:
  desc: null
  value: 1000
batch_size:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.2
    framework: huggingface
    huggingface_version: 4.35.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1705814942.199924
    t:
      1:
      - 1
      - 11
      - 33
      - 41
      - 49
      - 50
      - 53
      - 55
      - 71
      - 105
      2:
      - 1
      - 11
      - 33
      - 41
      - 49
      - 50
      - 53
      - 55
      - 71
      - 105
      3:
      - 16
      - 23
      4: 3.10.12
      5: 0.16.2
      6: 4.35.2
      8:
      - 1
      - 5
      13: linux-x86_64
